name: Publish to Expo Go

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Init EAS Project & Publish
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          npx eas-cli init --account rorolidalgo --non-interactive || true
          npx eas-cli update --auto --non-interactive --no-use-hermes
